### ISSUE TITLE
How to use RetroSom for my own files?

### ISSUE THREAD

**Issue by ATPs** [XiaoweiZhuJJ/RetroSom#1]
I found it hard to use.

**Comment by XiaoweiZhuJJ** [comment]
Sorry about the inconvenience. We have been upgrading the pipeline to RetroSomV2, which is still under lots of testing. If you are interested. I can share you a working copy through google drive.

**Comment by ATPs** [comment]
Thank you, Prof. Zhu. I would like to test it. I will contact you via email. Best!
